### ISSUE TITLE
Call from externally

### ISSUE THREAD

**Issue by abureviewer3** [opencartbrasil/opencart-rest-api#1]
Hi,
I'm new to opencart api and curl I'm trying to insert, updated and delete some table from external php through api your code helps me a lot to fulfill my requirements and can you provide me a sample code about product insert, updated and delete from external php.

Thank you for your great service.

**Comment by abureviewer3** [comment]
Sorry I forgot to see this documentation https://github.com/mevdschee/php-crud-api 
Thank you very much.

**Comment by v5mvidal** [comment]
:+1:
