### ISSUE TITLE
[bug] erro ao listar oc_category_description

### ISSUE THREAD

**Issue by marcossaoleo** [opencartbrasil/opencart-rest-api#11]
Mensagem de erro: Not found (1pk)
Versão 3.0.3.3

**Comment by v5mvidal** [comment]
Olá @marcossaoleo.

Essa mensagem ocorre exatamente onde?

**Comment by marcossaoleo** [comment]
Ao tentar listar várias descrições ou uma em especial. (mesmo procedimento dos produtos que está no exemplo, apenas alterando na url o nome tabela)

Produtos e categorias funcionam.

**Comment by MATOSTCI** [comment]
Not found (1pk) ao usar o PUT
Estou com esse problema com chave composta, quando não tem chave composta funciona 100% porém as que tem chave composta dão problema.
Vi outro colega lucaserlich  vez uma alteração mas parece que ela ainda não esta comitada, tentei usar como ele indicou mas sem sucesso.
ele propos da seguinte forma: 
http://www.loja.matostci.com.br/api.php/oc_category_description/4-1

Porém não encontrei esse arquivo alterado para baixar e testa-lo 

só esta faltando isso para terminar minha integração o restante esta ok

Pode me ajudar a corrigir esse questão ?

Aguardo re

**Comment by lucasgr7** [comment]
Boa noite pessoal, vi que mandaram um PR com uma suposta solução:https://github.com/opencartbrasil/opencart-rest-api/pull/13
Meu caso no momento infelizmente foi excluir destruir os indíces composts e recriar um simples. Funcionou, porém perdi suporte a multi-linguagem.

**Comment by alexandrofenner** [comment]
O PR ainda não foi aceito. mas existe um fork com o código alterado para suporte à pk composta
https://github.com/alexandrofenner/opencart-rest-api

neste fork para usar o valor da chave composta o valor da chave deve ser separado por ','

http://meusite.com.br/api.php/oc_category_description/1,2
