### ISSUE TITLE
duvida

### ISSUE THREAD

**Issue by ricardorohde** [opencartbrasil/opencart-rest-api#12]
não entendi muito bem essa parte

É necessário informar a sua Chave da API em todas as URLs da API que serão acessadas, passando-a no cabeçalho da requisição com o nome key tendo como valor a sua Chave da API.

Exemplo:
key = mMAnvMIaP7zPHnF7hBi23ebGyIU6sp2eWRfdi08yNWOo8wRXPAWgCol

isso seria em cada requisição???

**Comment by lucasgr7** [comment]
Sim, é basicamente um token fixo de autenticação que fica sendo enviado por parâmetro:

Segue exemplo em PHP:

```
<?php
require_once 'HTTP/Request2.php';
$request = new HTTP_Request2();
$request->setUrl('https://meusite.com.br/api.php/oc_product/713168502');
$request->setMethod(HTTP_Request2::METHOD_GET);
$request->setHeader(array(
  'key' => 'bC4vjtLUOREiSrrAHkIeD2D2rT7CA70kysYdugFnhuLN2vJuq0Ymrm9',
));
try {
  $response = $request->send();
  if ($response->getStatus() == 200) {
    echo $response->getBody();
  }
  else {
    echo 'Unexpected HTTP status: ' . $response->getStatus() . ' ' .
    $response->getReasonPhrase();
  }
}
```
