### ISSUE TITLE
suporte à pks compostas

### ISSUE THREAD

**Issue by alexandrofenner** [opencartbrasil/opencart-rest-api#15]
Por enquanto pode-se utilizar o fork https://github.com/alexandrofenner/opencart-rest-api para ter suporte à pks compostas

neste fork.. o valor da chave deve ser passado separado por ',' (vírgula)

https://meusite.com.br/api.php/oc_category_description/4,2

esperamos q o PR seja aceito..

**Comment by v5mvidal** [comment]
@alexandrofenner confirmei seu pull request, mas vamos mudar a versão do PHP-CRUD-API para v2, com o objetivo de manter atualizada e segura essa integração, ou seja, essa versão será descontinuada.

Se for possível realizar o mesmo trabalho de suporte para pks compostas na PHP-CRUD-API para v2, sua contribuição será bem vinda.
