### ISSUE TITLE
Multiplas Imagens

### ISSUE THREAD

**Issue by rfbastos** [opencartbrasil/opencart-rest-api#16]
É possível enviar múltiplas imagens via api para fazer uma galeria?

Como?

**Comment by v5mvidal** [comment]
Atualmente não é possível fazer upload das imagens, mas estamos trabalhando em uma nova API para a versão OpenCart Brasil, que será completa no cadastro de produtos, além de possuir recursos auxiliares como webhook.

**Comment by dicoretbr** [comment]
Eu faço o upload via FTP já com os caminhos definidos e devidamente informados pela API

**Comment by v5mvidal** [comment]
@dicoretbr é uma ótima forma de lidar com o cadastro de imagens.
