### ISSUE TITLE
The directory api.php is not allowed to be written to!

### ISSUE THREAD

**Issue by fsc7** [opencartbrasil/opencart-rest-api#5]
I am getting this error when trying to install in a clean 3.0 Opencart installation.
Any ideas?

**Comment by v5mvidal** [comment]
Version 3.0 has blocked some directories for extension files.

Let's upgrade

**Comment by logycware** [comment]
Hello, how can i install it manuality? I copied config_api.php and api.php to main folder, but it doesn't work cause is faulting some items on database and the key item on header is not recogmized.

Thanks.

**Comment by v5mvidal** [comment]
@logycware Read the entire user manual ;)
