### ISSUE TITLE
Usage :- Stuck 

### ISSUE THREAD

**Issue by KshitijBaluni** [opencartbrasil/opencart-rest-api#6]
https://github.com/opencartbrasil/opencart-rest-api#utilização-usage

Not Able to understand and implement it from here ,Please guide how to implement it from here.

Usage
**"You must enter your API Key in all API URLs that will be accessed by passing it in the request header with the name key having its API Key value."**

*Note Please help understand and implement these lines step by step in out opencart store, please do mention the folders and directories file path that need to be followed and where exactly the changes need to be made.
Where we need to this key parameter? In which file exactly. Constantly getting errors 
{ " API Error " : " Key not found! " }

Example:

Key = mMAnvMIaP7zPHnF7hBi23ebGyIU6sp2eWRfdi08yNWOo8wRXPAWgCol

Any kind of help will be appreciated.
Thanks and Regards,
Kshitij Baluni

**Comment by osworx** [comment]
Guess is fairly described here: https://github.com/opencartbrasil/opencart-rest-api#acesso-a-api-rest-do-opencart-access-to-the-rest-api-opencart
You have to add header[] to your request.

**Comment by KshitijBaluni** [comment]
Osworx Hi, Thanks for the reply mate. Finally done with the  opencart Rest API
