### ISSUE TITLE
{"API Error":"Key not found!"}

### ISSUE THREAD

**Issue by agenciaexpression** [opencartbrasil/opencart-rest-api#8]
Subi os arquivos, criei a API REST, gerei o token e habilitei a API.

Mas usando a requisição tanto por um plugin do firefox como pelo exemplo php, sempre me retorno o erro: {"API Error":"Key not found!"}

LEMBRANDO: Que estou passando o token no header, e no exemplo em php substitui o token. Esse erro trivial tenho certeza que não cometi.

**Comment by brunokunace** [comment]
Mesma coisa aqui, não importa o que vc faça, sempre retorna o erro

![image](https://user-images.githubusercontent.com/16597320/46539929-3d0d6780-c88e-11e8-838d-20fc2d143d02.png)


E se vc fizer algo como api.php/oc_product/
ele te envia pra página inicial da store (root do domain)

Esqueci de informar, estou utilizando o opencart 3

**Comment by brunokunace** [comment]
Quanto ao erro da api, encontrei o problema, o header agora por padrão vem como Key e nao key, então basta chamar o strtolower para não haver mais este problema no arquivo https://github.com/opencartbrasil/opencart-rest-api/blob/master/config_api.php#L108-L113

segue um exemplo
```
$headers = Database::getHeaders();
foreach ($headers as $name => $value) {
  $nameLower = strtolower($name);
  if ($nameLower == 'key') {
    $key = $value;
  }
} 
```

Porém continuar não chegando a informação nas tabelas, se eu fizer um domain/api.php/oc_product/ ele continua retornando para a homepage

@v5manoel Sabe me dizer se foi feita alguma mudança no router do opencart do 2.1 para o 3? Como comecei a mexer com ele agora, não sei ainda como o router dele funciona.

Obrigado.

**Comment by gessicadanielly** [comment]
Não sei se encontrou o erro, mas eu coloquei o SESSION_LOG como false e passou... o bug é quando entra na condição SESSION_LOG TRUE... tem que debbugar lá, caso o SESSION_LOG seja necessário pra vc.

**Comment by gessicadanielly** [comment]
Sobre  o bug com o SESSION_LOG: TRUE, no insert do log colocaram os campos token e session_name que não existem na tabela (oc_api_session). Eu retirei esses dois campos do insert e agora tá gravando o LOG e exibindo o JSON.

Meu config_api.php (Linha 140) ficou assim:

$sql = $conn->prepare("INSERT INTO `" . DB_PREFIX . "api_session` SET `api_id` = :api_id, `session_id` = :session_id, `ip` = :ip, `date_added` = NOW(), `date_modified` = NOW()");
$sql->bindParam(':api_id', $api_info->api_id, PDO::PARAM_INT);
$sql->bindParam(':session_id', $session_id, PDO::PARAM_STR);
$sql->bindParam(':ip', $_SERVER['REMOTE_ADDR'], PDO::PARAM_STR);
$sql->execute();

Antes estava assim:

$sql = $conn->prepare("INSERT INTO `" . DB_PREFIX . "api_session` SET `api_id` = :api_id, **`token` = :token**, **`session_name` = :session_name**, `session_id` = :session_id, `ip` = :ip, `date_added` = NOW(), `date_modified` = NOW()");
$sql->bindParam(':api_id', $api_info->api_id, PDO::PARAM_INT);
**$sql->bindParam(':token', $token, PDO::PARAM_STR);
$sql->bindParam(':session_name', $session_name, PDO::PARAM_STR);**
$sql->bindParam(':session_id', $session_id, PDO::PARAM_STR);
$sql->bindParam(':ip', $_SERVER['REMOTE_ADDR'], PDO::PARAM_STR);
$sql->execute();

Coloquei em **negrito** o que removi.

Outra opção seria criar essas duas colunas (token e session_name) na tabela.

**Comment by v5mvidal** [comment]
Olá @brunokunace 

Adicionei sua sugestão de melhoria na API. :)

**Comment by v5mvidal** [comment]
Olá @gessicadanielly 

Adicionei sua sugestão de melhoria como um novo recurso que pode ser ativado para OpenCart 3, ou seja, basta definir **OPENCART_V3** como **true** que o problema não vai mais acontecer.

Obrigado pela informação. :)
